export const QUERY_KEYS = {
  REBALANCER_WHITELIST: "rebalancer-whitelist",
  REBALANCER_ACCOUNT_CONFIG: "rebalancer-account-config",
  ACCOUNT_BALANCES: "account-balances",
  AUCTION_BALANCES: "auction-balances",
  AUCTION_STATUSES: "auction-statuses",
  HISTORIC_VALUES: "historic-values",
  WALLET_BALANCES: "wallet-balances",
  COINGECKO_PRICE: "coingecko-price",
  ORIGIN_ASSET: "origin-asset",
  VALENCE_ACCOUNT: "valence-account",
  HISTORIC_PRICES_COINGECKO: "historic-prices-coingecko",
  HISTORIC_PRICES_ORACLE: "historic-prices-oracle",
  HISTORIC_BALANCES: "historic-balances",
  HISTORIC_TARGETS: "historic-targets",
  COMBINED_HISTORIC_PRICES: "combined-historic-prices",
  COMBINED_HISTORICAL_VALUE_DATA: "combined-historical-values-data",
  HISTORICAL_GRAPH: "historical-graph",
  CREATE_PROJECTION_GRAPH: "create-projection-graph",
  REBALANCER_FORM_MESSAGE_PREVIEW: "rebalancer-form-message-preview",
};
