/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import {
  AuthorizationDuration,
  AuthorizationModeInfo,
  PermissionTypeInfo,
  Uint128,
  Expiration,
  Timestamp,
  Uint64,
  Priority,
  Subroutine,
  LibraryAccountType,
  Domain2,
  ParamRestriction,
  Binary,
  MessageType,
  Duration,
  RetryTimes,
  Addr,
  AuthorizationInfoUpdate,
  InstantiateMsg,
  ProgramConfig,
  AuthorizationData,
  AuthorizationInfo,
  AtomicSubroutine,
  AtomicFunction,
  MessageDetails,
  Message,
  RetryLogic,
  NonAtomicSubroutine,
  NonAtomicFunction,
  FunctionCallback,
  ProgramConfigUpdate,
  ExecuteMsg,
  QueryMsg,
} from "./ProgramConfigManager.types";
export interface ProgramConfigManagerReadOnlyInterface {
  contractAddress: string;
}
export class ProgramConfigManagerQueryClient
  implements ProgramConfigManagerReadOnlyInterface
{
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
  }
}
