/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from "./Account.types";
import * as _1 from "./Rebalancer.types";
export namespace contracts {
  export const Account = {
    ..._0,
  };
  export const Rebalancer = {
    ..._1,
  };
}
